### ISSUE TITLE
review for flex-2 task-1

### ISSUE THREAD

**Issue by asyncink** [supermanechka/learn-css#4]
1. Давай сделаем, чтобы задание располагалось по центру экрана
2. Лишняя пустая строка:
https://github.com/supermanechka/css-flexbox/blob/860acf3782337501528f7d9c89b2de0fc8237229/2-flex/1-task/styles.css#L29
3. У class-1 и class-2 много общих свойств:
https://github.com/supermanechka/css-flexbox/blob/860acf3782337501528f7d9c89b2de0fc8237229/2-flex/1-task/styles.css#L14-L22
https://github.com/supermanechka/css-flexbox/blob/860acf3782337501528f7d9c89b2de0fc8237229/2-flex/1-task/styles.css#L24-L33
Лучше их не писать два раза:

   ``` css
   .class-1, .class-2 {
      width: 136px;
      height: 103px;
     ...
   }
   ```

   А потом отдельно для каждого класса установить фон.
